apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simple-api
  annotations:
    app.kubernetes.io/name: nginx
spec:
  rules:
  - host: simple-api.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple-api-service
            port: 
              number: 80
